import {z} from "zod";
import { parse } from 'jsonc-parser';
require('dotenv').config();

import FUAFormatImplementation from '../implementation/sequelize/FUAFormatImplementation';
import { generateSHA256Hash, isValidUUIDv4 } from "../utils/utils";
import FUARenderingUtils from "../utils/FUARendering";
import FUAFormatFromSchemaImplementation from "../implementation/sequelize/FUAFormatFromSchemaImplementation";
import { inspect } from "util";
import BaseEntityVersionImplementation, { relatedEntity } from "../implementation/sequelize/BaseEntityVersionImplementation";
import { generateHMAC } from "../modelsSequelize/utils";
import BaseEntity from "../modelsTypeScript/BaseEntity";


function isBaseEntity(obj: unknown): obj is BaseEntity {
  return obj instanceof BaseEntity;
}

// Schemas

const newFUAFormatFromSchemaZod = z.object({
    // Format Data
    name: z.string(),
    content: z.string(),
    // Base Field Form Data
    codeName: z.string(),    
    versionTag: z.string(),
    versionNumber: z.number().int().positive(), // must be a positive integer
    // Audit Data
    createdBy: z.string(),
});

const editBaseEntityVersionFromSchemaZod = z.object({
    // Format Data
    uuid: z.string(),
    name: z.string(),
    content: z.string(),
    // Base Field Form Data
    codeName: z.string(),    
    versionTag: z.string(),
    versionNumber: z.number().int().positive(), // must be a positive integer
    // Audit Data
    createdBy: z.string(),
});

class BaseEntityVersionService {

    // Creation of BaseEntityVersion
    async create(        
        data : any,                         // Generic entity that comes from BaseEntity, pending to change
        type : string,                  
        action: string,
        newRelatedEntities? : Array<relatedEntity>
    ) {
        if(!isBaseEntity(data)){
            let auxError = new Error('Object received doesnt come form BaseEntity. ');
            throw auxError;
        }
        /*
        class FUAMapping extends BaseEntity{
        
        }
        */
        data = (data as BaseEntity);
        // Object Validation

        /* const result = newFUAFormatFromSchemaZod.safeParse(data);
        if( !result.success ){
            const newError = new Error('Error in BaseEntityVersion Service - create: ZOD validation. ');
            (newError as any).details = result.error;
            throw newError;
        } */
        
        // Gedatanerate Hash
        let newHash = generateSHA256Hash(data.uuid+data.updatedAt+JSON.stringify(data.content)+data.action+(process.env.HMAC_SECRET ?? 'fuagenerator'));
        
        // BaseEnitityVersion creation

        let newData = {
            ...data,
            uuidEntity: data.uuid,
            versionCounter: 1, // Hardcoded value
            type: type,
            hash: newHash,
            action: action,
            content: JSON.stringify(data),
            relatedEntities: newRelatedEntities,
        }
        // We delete id if already exists because he needs to be autogenerated by the DB
        if ((newData as any).id !== undefined) {
            delete (newData as any).id;
        }
        //We do the same for the uuid
        if ((newData as any).uuid !== undefined) {
            delete (newData as any).uuid;
        }

        let newVersion = null;
        try {
            newVersion = await BaseEntityVersionImplementation.createSequelize(newData);
        } catch (err: any){
            (err as Error).message = 'Error in BaseEntityVersion Service: ' + (err as Error).message;
            const long = inspect(err, { depth: 10, colors: false });
            (err as any).details = (err as any).details ?? long;
            throw err;
        }

        return {
            uuid: newVersion.uuid
        };
    };

    // List FUA Formats
    // Pending to paginate results
    async listAll( ) {
        let returnedFUAFormats = [];
        try {
            returnedFUAFormats = await FUAFormatFromSchemaImplementation.listAllSequelize();

        } catch (err: any){
            (err as Error).message =  'Error in FUA Format From Schema Service: ' + (err as Error).message;
            throw err;
        }        

        return returnedFUAFormats;
    };

    // Get FUA Format by Id (Id or UUID)
    async getByIdOrUUID( idReceived: string ) {
        let returnedFUAFormat = null;

        // Check if UUID or Id was sent
        let id = null;
        const nuNumber = Number(idReceived);
        if( Number.isInteger(nuNumber) ){
            id = nuNumber;

            try {
                returnedFUAFormat = await FUAFormatFromSchemaImplementation.getByIdSequelize(id);

            } catch (err: unknown){
                (err as Error).message =  'Error in FUA Format From SchemaFUA Format From Schema Service: ' + (err as Error).message;
                throw err;
            }     
        }else{
            // Get id by UUID
            //Validate UUID Format        
            if (!isValidUUIDv4(idReceived) ) {
                throw new Error("Error in FUA Format From Schema Service: Invalid UUID format. ");
            }
            try {

                returnedFUAFormat = await FUAFormatFromSchemaImplementation.getByUUIDSequelize(idReceived);

            } catch (err: unknown){
                (err as Error).message =  'Error in FUA Format From Schema Service: ' + (err as Error).message;
                throw err;
            }
            
        }      
        // If nothing was offund, return a null
        return returnedFUAFormat;
    };

    // Get FUA Format Id by UUID
    async getIdByUUID( uuidReceived: string){
        let returnedFUAFormats = null;

        //Validate UUID Format        
        if (!isValidUUIDv4(uuidReceived) ) {
            throw new Error("Error FUA Format From Schema Service - getIdByUUID: Invalid UUID format. ");
        }

        try {
            returnedFUAFormats = await FUAFormatFromSchemaImplementation.getByUUIDSequelize(uuidReceived);

        } catch (err: unknown){
            console.error('Error in FUA Format From Schema Service - getIdByUUID: ', err);
            (err as Error).message =  'Error in FUA Format From Schema Service- getIdByUUID: ' + (err as Error).message;
            throw err;
        }

        // If nothing was found, it will return a null
        return returnedFUAFormats
    }

    // Render FUA Format by Id
    async renderById( visitPayload: Object, idReceived: string ) {
        // Get Format by Id or UUID
        let auxFuaFormat = null;
        try {
            auxFuaFormat = await this.getByIdOrUUID(idReceived);
        } catch (err: unknown){
            console.error('Error in FUAFormat Service - renderById: ', err);
            (err as Error).message =  'Error in FUAFormat Service - renderById: ' + (err as Error).message;
            throw err;
        }

        // If nothing was found, it will return a null
        if( auxFuaFormat === null){
            return null;
        } 

        let htmlContent = ''; 

        let parsedContent = parse(auxFuaFormat.content);

        try{
            htmlContent = await FUARenderingUtils.renderFUAFormatFromSchema(parsedContent, false);
        } catch(error: any){
            (error as Error).message =  'Error in FUA Format Service - renderById: ' + (error as Error).message;
            const line = inspect(error, { depth: 100, colors: false });
            error.details = line.replace(/^/gm, '\t');
            throw error;
        }
        
        
        return htmlContent;   
    }


};

export default new BaseEntityVersionService();
